#!/usr/bin/env python

import dropbox
import os
from zipfile import ZipFile

TOKEN = os.environ.get('DBX_TOKEN')
print('DOWNLOADING FILES --------------')
dbx = dropbox.Dropbox(TOKEN)
result = dbx.files_download_zip_to_file('temp.zip','/world')
with ZipFile('temp.zip', 'r') as zipObj:
    for fileName in zipObj.namelist():
        if 'world/' in fileName:
            zipObj.extract(fileName)
os.remove('temp.zip')

print('FINISHED DOWNLOADING FILES --------------')