#!/usr/bin/env bash

if [ -n "$DBX_TOKEN" ]; then
#   cat << EOF > .s3cfg
# [default]
# access_key = ${AWS_ACCESS_KEY}
# secret_key = ${AWS_SECRET_KEY}
# EOF
  if [ -d world ]; then
    bin/upload
  else
    bin/download
  fi
#   rm .s3cfg
fi
