#!/usr/bin/env python

import os
import sys

import dropbox
from dropbox.files import WriteMode
from dropbox.exceptions import ApiError

# OAuth2 access token.  TODO: login etc.
TOKEN = os.environ.get('DBX_TOKEN')


def main():
    """Main program.
    """
dbx = dropbox.Dropbox(TOKEN)

# get an access token, local (from) directory, and Dropbox (to) directory
# from the command-line
local_directory, dropbox_destination = 'world', 'world'

# enumerate local files recursively
for root, dirs, files in os.walk(local_directory):

    for filename in files:

        # construct the full local path
        local_path = os.path.join(root, filename)

        # construct the full Dropbox path
        relative_path = os.path.relpath(local_path, local_directory)
        dropbox_path = '/'+os.path.join(dropbox_destination, relative_path).replace(os.path.sep,'/')

        # upload the file
        mode = WriteMode.overwrite
        with open(local_path, 'rb') as f:
            data = f.read()
        try:
            res = dbx.files_upload(
                data, dropbox_path, mode,
                mute=True)
        except dropbox.exceptions.ApiError as err:
            print('*** API error', err)
        print('uploaded as', res.name.encode('utf8'))

if __name__ == '__main__':
    main()